spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sportbuddyd&useSSL=false
    username: sportbuddy_dev
    password: sportbuddy
    platform: postgres

  devtools:
    add-properties: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgres
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql