--## Use to run postgres db docker image
--# docker-compose -f stack.yml up

--#Create database and service accounts (login with super account in order to do this!)
CREATE database sportbuddydb;

CREATE USER sportbuddy_prod WITH PASSWORD 'sportbuddy';
CREATE USER sportbuddy_dev WITH PASSWORD 'sportbuddy';

--#Creating schemas with owners (select database)

CREATE SCHEMA sb_prod AUTHORIZATION sportbuddy_prod;
CREATE SCHEMA sb_dev AUTHORIZATION sportbuddy_dev;

GRANT CONNECT ON DATABASE sportbuddydb TO sportbuddy_dev;
GRANT CONNECT ON DATABASE sportbuddydb TO sportbuddy_prod;

GRANT ALL ON schema sb_dev TO sportbuddy_dev;
GRANT ALL ON schema sb_prod TO sportbuddy_prod;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sb_dev TO sportbuddy_dev;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sb_prod TO sportbuddy_prod;

-- #If necessary:
--GRANT USAGE ON SCHEMA sb_dev TO sportbuddy_dev;
--GRANT USAGE ON SCHEMA sb_prod TO sportbuddy_prod;

--#Initial data to be created in each schema:

create table client (id bigint generated by default as identity, email varchar(255), name varchar(255), primary key (id));
create table client_participating_matches (user_id bigint not null, participating_matches_id bigint not null);
create table login_access (id bigint generated by default as identity, password varchar(255), username varchar(255), user_id bigint, primary key (id));
create table match (id bigint generated by default as identity, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants integer not null, ownerid bigint, owner_name varchar(255), sport_name varchar(255), primary key (id));
create table match_users_attending (match_id bigint not null, users_attending_id bigint not null);
create table user_favourite_sports (user_id bigint not null, favourite_sports varchar(255));
alter table client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references match;
alter table client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references client;
alter table login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references client;
alter table match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references client;
alter table match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references match;
alter table user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references client;
