create table client (id bigint generated by default as identity, email varchar(255), name varchar(255), primary key (id));
create table client_participating_matches (user_id bigint not null, participating_matches_id bigint not null);
create table login_access (id bigint generated by default as identity, password varchar(255), username varchar(255), user_id bigint, primary key (id));
create table match (id bigint generated by default as identity, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants integer not null, ownerid bigint, owner_name varchar(255), sport_name varchar(255), primary key (id));
create table match_users_attending (match_id bigint not null, users_attending_id bigint not null);
create table user_favourite_sports (user_id bigint not null, favourite_sports varchar(255));
alter table client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references match;
alter table client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references client;
alter table login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references client;
alter table match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references client;
alter table match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references match;
alter table user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references client;create table sb_dev.client (id  bigserial not null, email varchar(255), name varchar(255), primary key (id))


create table sb_dev.client_participating_matches (user_id int8 not null, participating_matches_id int8 not null)
create table sb_dev.login_access (id  bigserial not null, password varchar(255), username varchar(255), user_id int8, primary key (id))
create table sb_dev.match (id  bigserial not null, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants int4 not null, ownerid int8, owner_name varchar(255), sport_name varchar(255), primary key (id))
create table sb_dev.match_users_attending (match_id int8 not null, users_attending_id int8 not null)
create table sb_dev.user_favourite_sports (user_id int8 not null, favourite_sports varchar(255))
alter table sb_dev.client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references sb_dev.match
alter table sb_dev.client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references sb_dev.client
alter table sb_dev.login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references sb_dev.match
alter table sb_dev.user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references sb_dev.client
create table sb_dev.client (id  bigserial not null, email varchar(255), name varchar(255), primary key (id))
create table sb_dev.client_participating_matches (user_id int8 not null, participating_matches_id int8 not null)
create table sb_dev.login_access (id  bigserial not null, password varchar(255), username varchar(255), user_id int8, primary key (id))
create table sb_dev.match (id  bigserial not null, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants int4 not null, ownerid int8, owner_name varchar(255), sport_name varchar(255), primary key (id))
create table sb_dev.match_users_attending (match_id int8 not null, users_attending_id int8 not null)
create table sb_dev.user_favourite_sports (user_id int8 not null, favourite_sports varchar(255))
alter table sb_dev.client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references sb_dev.match
alter table sb_dev.client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references sb_dev.client
alter table sb_dev.login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references sb_dev.match
alter table sb_dev.user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references sb_dev.client

create table sb_dev.client (id  bigserial not null, email varchar(255), name varchar(255), primary key (id))
create table sb_dev.client_participating_matches (user_id int8 not null, participating_matches_id int8 not null)
create table sb_dev.login_access (id  bigserial not null, password varchar(255), username varchar(255), user_id int8, primary key (id))
create table sb_dev.match (id  bigserial not null, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants int4 not null, ownerid int8, owner_name varchar(255), sport_name varchar(255), primary key (id))
create table sb_dev.match_users_attending (match_id int8 not null, users_attending_id int8 not null)
create table sb_dev.user_favourite_sports (user_id int8 not null, favourite_sports varchar(255))
alter table sb_dev.client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references sb_dev.match
alter table sb_dev.client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references sb_dev.client
alter table sb_dev.login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references sb_dev.match
alter table sb_dev.user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references sb_dev.client
create table sb_dev.client (id  bigserial not null, email varchar(255), name varchar(255), primary key (id))
create table sb_dev.client_participating_matches (user_id int8 not null, participating_matches_id int8 not null)
create table sb_dev.login_access (id  bigserial not null, password varchar(255), username varchar(255), user_id int8, primary key (id))
create table sb_dev.match (id  bigserial not null, date varchar(255), details varchar(255), hour varchar(255), location varchar(255), name varchar(255), number_of_participants int4 not null, ownerid int8, owner_name varchar(255), sport_name varchar(255), primary key (id))
create table sb_dev.match_users_attending (match_id int8 not null, users_attending_id int8 not null)
create table sb_dev.user_favourite_sports (user_id int8 not null, favourite_sports varchar(255))
alter table sb_dev.client_participating_matches add constraint FKt1nipt8i3i4cgkiul82l1gjg9 foreign key (participating_matches_id) references sb_dev.match
alter table sb_dev.client_participating_matches add constraint FK5dtxso2dstbrjh92klt6qg8k6 foreign key (user_id) references sb_dev.client
alter table sb_dev.login_access add constraint FKfo8evr2pgvi8vbbscf39eh18h foreign key (user_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FKnrwv4yvehj7k4mjap3ohonk0 foreign key (users_attending_id) references sb_dev.client
alter table sb_dev.match_users_attending add constraint FK1356ow2vv8yuejj1j8bg5vpqe foreign key (match_id) references sb_dev.match
alter table sb_dev.user_favourite_sports add constraint FKqbdiu1b7toxffhw31w2y1iht1 foreign key (user_id) references sb_dev.client
